### ISSUE TITLE
Update Website URL in Youw GitHub Pwofile

### ISSUE THREAD

**Issue by MikuChan04** [IdefaSoft/Softwares#1]
Watashi would like to wequest a change in the website URL displayed in youw GitHub pwofile. The cuwwent website URL is "idefasoft.github.io," and watashi would like it to be updated to "idefasoft.fr"

**Steps to Reproduce:**
1. Go to youw GitHub pwofile. O.O
2. Click on "Edit Pwofile."
3. In the "Website" field, senpai will find the cuwwent URL as "idefasoft.github.io." (´∩｡• ᵕ •｡∩`)
4. Replace it with the new URL, "idefasoft.fr." 😊😊😊
5. Save the changes. (*≧ω≦)

**Expected Result:**
The website URL in youw GitHub pwofile should be updated to "idefasoft.fr" (*≧ω≦)
 (´∩｡• ᵕ •｡∩`)
onegai make this change as soon as possible. Thank senpai! Onegai accept my pull reqwest >.<

**Comment by idefasoft** [comment]
Hey, thanks for letting me know! :)
I've fixed the "issue". 👍 
Cya !

**Comment by MikuChan04** [comment]
Thanks Senpai UwU >.<
